-- MySQL Script generated by MySQL Workbench
-- Sun Jun  4 12:59:28 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gerenciamentocontas
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gerenciamentocontas
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gerenciamentocontas` DEFAULT CHARACTER SET utf8 ;
USE `gerenciamentocontas` ;

-- -----------------------------------------------------
-- Table `gerenciamentocontas`.`Pessoa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gerenciamentocontas`.`Pessoa` ;

CREATE TABLE IF NOT EXISTS `gerenciamentocontas`.`Pessoa` (
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CPF`, `Nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentocontas`.`ContaCorrente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gerenciamentocontas`.`ContaCorrente` ;

CREATE TABLE IF NOT EXISTS `gerenciamentocontas`.`ContaCorrente` (
  `NumeroConta` INT NOT NULL AUTO_INCREMENT,
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `saldo` FLOAT DEFAULT(0),
  `ChequeEspecial` FLOAT DEFAULT(0),
  PRIMARY KEY (`NumeroConta`, `Nome`, `CPF`)
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gerenciamentocontas`.`ContaPoupanca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `gerenciamentocontas`.`ContaPoupanca` ;

CREATE TABLE IF NOT EXISTS `gerenciamentocontas`.`ContaPoupanca` (
  `NumeroConta` INT NOT NULL AUTO_INCREMENT,
  `CPF` INT NOT NULL,
  `Nome` VARCHAR(45) NOT NULL,
  `saldo` FLOAT DEFAULT(0),
  `taxa` FLOAT DEFAULT(0),
  PRIMARY KEY (`NumeroConta`, `Nome`, `CPF`)
)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `gerenciamentocontas`.`log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gerenciamentocontas`.`log` (
  `id_log` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `log` VARCHAR(300) NOT NULL,
  `tabela` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_log`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
